import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Header from '../components/landing-page/header'

const albra = localFont({
  src: '../../public/fonts/Albra-400.otf',
  variable: '--font-albra',
})

const bergenRegular = localFont({
  src: '../../public/fonts/Bergen-Mono-400.otf',
  variable: '--font-bergen-regular',
})

const bergenSemibold = localFont({
  src: '../../public/fonts/Bergen-Mono-600.otf',
  variable: '--font-bergen-semibold',
})

const windsorPro = localFont({
  src: '../../public/fonts/Windsor-Pro-400.ttf',
  variable: '--font-windsor-pro',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${albra.variable} ${bergenRegular.variable} ${bergenSemibold.variable} ${windsorPro.variable} antialiased text-brain-text`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
